sudo: true
dist: trusty
language: node_js
node_js:
- node
jobs:
  include:
  - stage: "@narragen/parser"
    install:
    - npm install --prefix packages/parser
    script:
    - npm run-script compileBabel --prefix packages/parser
    - npm run-script compileUglifyJs --prefix packages/parser
    - npm test --prefix packages/parser
    deploy:
    - provider: script
      script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/parser
      skip_cleanup: true
      on:
        branch: master
        repo: jameswilddev/narragen
env:
  global:
  - secure: k6IuS6ZJMbuMeUcSmRY7aL7X+rrr/M9mey8k3iR0ctUDGpx8FE/qnqMNLiRYV3+V0032cSy4vW5eH5HkYF9al532ZXFZP2KlDHH+vp4IDVmEDOsqJqwPtzVVvZYysWEakObTNWbQIvgAk3QxOHlG2aa7E3gTCoXyCh5aY7gtDH68RrRnqjOjnf9W+Ki4YWuoTzYb+u29OrGYwxzvBuyPuJobFYmLLxsJONSpRFIXjoXAI228PfnGIG6BNVgmhneU5rHcm0kC1KWedWqqCxXaCUhVpXrEW0y+X4QzHhCBuM8hTRsrZKmAIomplhzA1z9t7znHriOtPxalz9B5X6QdxJ5KDFbdifRxJP/t4KL5sfkv87tUjfDNVoxRaJ+Jq9jr+DOveyAPZui71snVSITu7gLsIHo3EUgDvDsQ5zIb6qmT75o9EtaenkNcj5FuszN6IoHh13pXBjwLE2fP0JpRuGz0bI4jHNdFwI/XG0RTfx6sS5khizd/uoiNjJ7q9aqwbFJg3qZsjQT0HZ6ZqmoYM0d3aOQNwzzuJgStH1xNMpkHVayg1HGgxz2Y4vAAfY9rUOKKFAW3uy/SRCkkZP/eVbzgGFQmhnnSkDFAZrIL2TSPasGnqUm7rPou3vXXNoBF2qz+vE08mUQRIT7C74MI50/oQIJtHFowtN3hTCAcOtc=
  - secure: f9sszLBVY+xWH0qf6OO2pSZe2OZIk/5h1vBqY3y6hiq05KOLvCplcUCy+w2piCk+6zBOhWeTKEv5pex99a3SOpNBhKzDtSRO5ECS0cra4KMwWwuJJU7u0kFn/+yyq+ew1YlZVAnqAwDOwSSY4vHWk7cH1PMpaLaBAiX/yqX0BR4SGC+JdHde2SxbkPwqUI82GuML1FONheTgVfb1Fw+sjNN2keyZfW6NAk4eaiLfoAHqPoKOjcLMaXOZ0ntaz166XWEDJmzP19VaXB3R6a+SxVVsWOmgzawV2j4XGasEMZColkMtgihBYitjrTl1WJcTtsgXqD1A7ugBTyXLQY6nc0PyrzJ4Ep8LLMg0x0tMhAVaEz72tQaLZOtJfhrKN9f3WZwSTtHVkg8yzRGhtDUmlPPJ2sueRuVMjx7ua3GVkNqQtv0p+ofchc4FegwSGON5W5tXwHAlNkYtcXxuzhykE2hRPch+IySvh49JbOE6RHO0e3WyZ7k72lxC3Oq7cJOUATYT7OySeYS07CaZBYCnp/0A4A/A/3m8QOR2hzC8uwjwA9dODHJHVcqdGobzHHudcOwO6P9ZRqTMCCKxGOTShieMs6NlU8Iko1J5tlA4SiaEE7zsWlAqbhcAC1CRRjKsEwntQcQbzAUYA7vzb9EPKFOUb/tILb7cc7ywXQokrXE=
