sudo: true
dist: trusty
language: node_js
node_js:
- node
jobs:
  include:
  - stage: "@narragen/parser"
    install:
    - npm install --prefix packages/parser
    script:
    - npm run-script compileBabel --prefix packages/parser
    - npm run-script compileUglifyJs --prefix packages/parser
    - npm test --prefix packages/parser
    deploy:
    - provider: script
      script: echo $NPM_AUTH > ~/.npmrc && npm publish packages/parser
      skip_cleanup: true
      on:
        branch: master
        repo: jameswilddev/narragen
env:
  global:
  - secure: k6IuS6ZJMbuMeUcSmRY7aL7X+rrr/M9mey8k3iR0ctUDGpx8FE/qnqMNLiRYV3+V0032cSy4vW5eH5HkYF9al532ZXFZP2KlDHH+vp4IDVmEDOsqJqwPtzVVvZYysWEakObTNWbQIvgAk3QxOHlG2aa7E3gTCoXyCh5aY7gtDH68RrRnqjOjnf9W+Ki4YWuoTzYb+u29OrGYwxzvBuyPuJobFYmLLxsJONSpRFIXjoXAI228PfnGIG6BNVgmhneU5rHcm0kC1KWedWqqCxXaCUhVpXrEW0y+X4QzHhCBuM8hTRsrZKmAIomplhzA1z9t7znHriOtPxalz9B5X6QdxJ5KDFbdifRxJP/t4KL5sfkv87tUjfDNVoxRaJ+Jq9jr+DOveyAPZui71snVSITu7gLsIHo3EUgDvDsQ5zIb6qmT75o9EtaenkNcj5FuszN6IoHh13pXBjwLE2fP0JpRuGz0bI4jHNdFwI/XG0RTfx6sS5khizd/uoiNjJ7q9aqwbFJg3qZsjQT0HZ6ZqmoYM0d3aOQNwzzuJgStH1xNMpkHVayg1HGgxz2Y4vAAfY9rUOKKFAW3uy/SRCkkZP/eVbzgGFQmhnnSkDFAZrIL2TSPasGnqUm7rPou3vXXNoBF2qz+vE08mUQRIT7C74MI50/oQIJtHFowtN3hTCAcOtc=
  - secure: JlmB4klmOftStQ0MQwNo72U2+tHN4paEfDS7JX8XljTegKxSA2KpQ9Ar0dok5NtPYLXU9XWXK70QCczxGwcmf+Gu4Px8kedYp7hJCrPHN0shNHQavno9XhgN011VR8oAVKJFe/tcrbNWQMo9+kjC9twmDjPK3Ueb+NQc9wGJCPHQtMaZJVxGXgFkp7O/92ndbG/JGsHNitI7mHbTXNGgTVFAgBYGzXr13pz+C1a3jmURZMf3SYsyYUif4LMkVarlHYj3uafMxoTK13FKog3TbvlmjpZlD19NcdNTjjr42ebK0qxEMChhAKFRb0EoBK3y+/21+m4ir0fTlKK3HGhwTIPKMQMV6RaFE9z+cvEHDioXDCzuY42WcX2twivLOgUgMIlcc10/fV/QJ8m72wsHdDr3LhPF0EIZc4VhMDahCoYEzq0v6Udv6NrxSFAi2PImZmsfFPRL2TibknUHH3RF7afGDy2flocBKVsBYy8LSgn6/EAMVAjG1QFK/co9bXDQCRNv8aTWdWpiRJ0jQZZC4WfJXIgJnlDI0ir+5K57EgLoJrO5T53nm5OAoXNRorphrF2PEXqqPBknwV8afxtdyMay0VvoLy6fdj0wIUU2tyrsS0qPx5EKklIatSEe5ksUZ5e9WSGiOHzpMe2+TpCScGvL49Wiz6V0BKdRgFbPGjs=
