language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - npm run-script make-dist
  - npm run-script concatenate-module
  - npm run-script concatenate-helpers
  - npm run-script concatenate-tests
  - npm run-script jshint-module
  - npm run-script jshint-helpers
  - npm run-script jshint-tests
  - npm run-script babel-module
  - npm run-script babel-helpers
  - npm run-script babel-tests
  - npm run-script jasmine
  - npm run-script coveralls
  - npm run-script uglify
deploy:
  provider: npm
  email:
    secure: "SmwM7kdv7pdcRha2q8TErD1tsF97UYdiw5Z8OCAbUxD8SG+F6hR52z1vIDiKWhtKQj/98rjcF/co+yml+AafT83gjf5Fz9exfdtyXhkULjgq3vElB4+DIdfclvevyAs+AEh4XgLF8clRR+6OGy1gxpgFiZQvwTZQNWJE1sDkdFKodKXwvRpd+OdJ/Br6tFVIZeENigMjRksLap9hEXLv5a+kXiMcnIe4Lw9FRJKiD4MB/SdAAciEyh+vUfEEChC/Phjl+sRGdU/qu8vB4MqGXuCLLwR0DjAmGPTtmYpIfuIl04KABLyxT23p0DYyJ34vj/xqsESzk0MpH+ZLp3m32KJMO/akLe0z20HMQZN3V1P4Oyq81qgizEvVOIj+8YLuvstL6eKCgiXKFBt6RriBhhwroD3HopY6vZAevfPUMDzNab83lhl306ZLsPAT8ZuU/4W4q+P/mfuJjzKyZxpFH3O2mlQtDLdppQvlXPan1LyRCcL1EwPiHLp+pH+hbvm1egz3s5Fi1hlH9lGt6lWk7hbspyS6YVYC7e7YCBPijVihQuRnyCsjSEcQl7kkDPoWCW6QUnYmI0AxttBAqxxfxdQc8wF7dMQvA2eYIrJG2nlpg9EQ9j19yzt6j/lMivfivgK7OLdjvKl8LoJ6OQYwdW5JtlJZVUvfszFfas5Hknk="
  api_key: 
    secure: "JdeKyXTjN5k1LUQhqpBqVGORaLCijf6V3jGiUVrib/8/RrEGFa9/owl8aIHXLUJyINUjEkyGQEECNb2S2xXjUNw42fcFKXAsFasmCTJkicw2BGaxOBztlTTz1fC4X11hU6p1U5B4hQxoK7qmtGsqSj2GXd9JQRkQirisz/LVZxJPgGcRkByqCCOgB8bwU1ISz/lHnjqYd0KgFGX17QiVwwV6P3hO8ymUjCZ2OxuHHpqmbkLm0Wy/wGcdP1APT7bDnGi9OQUDkIabj0R2sESb/ufayzb5kM+pZgu0RzCvH3GwIsyEvq85evWY62wQZ+K6Y8XPb4lQRehDOfi+tRgGBbiCqZRBlnGz55049Uid15xygmgmf+JJCMjHd9y3koKYfyVa9gBp9N5CssmAa9ACqnfP3M0eyBYXlUW8ptC+Wu1cyfXIlFxT4zRQW1bR0rEUmhnk7zj0TaxKP/inemfq5ygnyv97umW5F7qhZptk3JjX2Mx/BHML8AbvV5OecisshJskCwxXlQJ3HoW+JLiJWzjetwebhUE3ApSoRH6/JmGQbBCeur9YAj42rsahTp3j0Q7qYXc2B0FIDNhbjYoepj/mNwRJ06SMugGOtVJp1HJ6EzIc+LGRptb+SzlngWfXW+0jCfAKWhRQGqG3TxPXT6NXe9YwZurqdnsPEo7NZdw="
  clean_up: false
  on:
    branch: master
    repo: jameswilddev/narragen